### ISSUE TITLE
Create a requirements.txt of all libraries and versions needed to run the assistant.

### ISSUE THREAD

**Issue by luminousbeam** [Veershah26/virtual-assistant#11]

**Comment by sabderemane** [comment]
Hi @luminousbeam , I've created a PR for this issue, tell me if you need me to change something to fit the need.

**Comment by luminousbeam** [comment]
@sabderemane, I created this Issue as a suggestion, but the owner of the repo is @Veershah26. He would be the one to review and approve this. @Veershah26 please take a look.
