### ISSUE TITLE
StressBusters

### ISSUE THREAD

**Issue by aditya9110** [Veershah26/virtual-assistant#17]
A program that reminds the user by notifying them to get away from the digital screen and enjoy the fresh air.
It stresses the **20-20-20 Rule**.
Every 20 minutes focus at a distance of 20 feet away for 20 seconds.
The program will also get trigger every time the system boots so that the user doesn't need to run it.

**Comment by Veershah26** [comment]
Would you want to work on this ? @aditya9110

**Comment by aditya9110** [comment]
@Veershah26 yes Sir, I would like to work on this topic.

**Comment by aditya9110** [comment]
@Veershah26 as my request is merged, should I close this issue?
