### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by EFFLUX110** [Veershah26/virtual-assistant#34]
No return type in [StressBusters](https://github.com/Veershah26/virtual-assistant/blob/main/modules/StressBusters.py) function.
Its creating `code is unreachable` for below functions in `main.py` file. 
_Here is the link to the line: _ https://github.com/Veershah26/virtual-assistant/blob/main/main.py#L93

**Comment by Veershah26** [comment]
Done @Pikel1997
