### ISSUE TITLE
We can also add youtube video downloader.

### ISSUE THREAD

**Issue by CS-Aditya-Rawat** [Veershah26/virtual-assistant#8]
I want to work on this enhancement. I will make a function which take the url of youtube video and download the video in local.

**Comment by Veershah26** [comment]
sure, then, ill assign the issue to you. Just a heads up, if you work on this, please create a file inside the modules folder and add it in a class. Have a great time coding and have a great hacktoberfest

**Comment by CS-Aditya-Rawat** [comment]
Close this issue as this enhancement is completed.
